// ─────────────────────────────────────────────
// dungeon_defs.js  ダンジョン定義
// ─────────────────────────────────────────────

// ボスラッシュ専用ボス名（波ごとに変わる）
export const BOSS_RUSH_NAMES = [
  '守護者ゴルバ', '鉄壁の番人', '血染めの爪', '魔将ブレイク',
  '深淵の眼', '嵐の覇者', '焦熱のタイラント', '無限の悪霊',
  '虚空の支配者', '時の終焉者',
];

export const DUNGEONS = [
  {
    id: 'cave',
    name: '初心者の洞窟',
    emoji: '🕳',
    maxFloors: 5,
    theme: 'dungeon',
    enemyTypes: ['slime', 'giant_rat', 'bat', 'kobold', 'goblin', 'cave_spider', 'skeleton', 'rock_crab', 'poison_slime'],
    enemyCountBase: 6,
    diffMult: 0.6,
    bossName: '巨大スライム',
    color: '#94a3b8',
    desc: '洞窟の基本モンスター。5階まで。初心者向け。',
  },
  {
    id: 'goblin_nest',
    name: 'ゴブリンの巣',
    emoji: '👺',
    maxFloors: 8,
    theme: 'dungeon',
    enemyTypes: ['goblin', 'archer', 'hobgoblin', 'goblin_shaman', 'goblin_bomber', 'wolf', 'orc', 'gnoll', 'goblin_chief', 'bandit', 'skeleton_archer'],
    enemyCountBase: 10,
    diffMult: 1.0,
    bossName: 'ゴブリンキング',
    color: '#22c55e',
    desc: 'ゴブリン族の巣。8階まで。中級者向け。',
  },
  {
    id: 'cursed_forest',
    name: '呪われた森',
    emoji: '🌲',
    maxFloors: 10,
    theme: 'forest',
    enemyTypes: ['zombie', 'ghost', 'forest_witch', 'werewolf', 'treant', 'poison_spider', 'giant_bat', 'skeleton_archer', 'dark_elf', 'shadow_assassin', 'cultist', 'dire_wolf', 'wraith'],
    enemyCountBase: 12,
    diffMult: 1.4,
    bossName: '呪いの樹霊',
    color: '#4ade80',
    desc: '呪われた生き物が潜む森。10階まで。上級者向け。',
  },
  {
    id: 'abyss',
    name: '奈落の城',
    emoji: '🏰',
    maxFloors: 15,
    theme: 'dungeon',
    enemyTypes: ['death_knight', 'void_crawler', 'fire_elemental', 'ice_elemental', 'thunder_elemental', 'vampire', 'lich', 'soul_eater', 'void_stalker', 'iron_golem', 'nightmare', 'chaos_mage', 'stone_golem', 'gargoyle', 'dark_slime', 'sniper', 'crossbowman', 'demon'],
    enemyCountBase: 15,
    diffMult: 2.2,
    bossName: '深淵魔王',
    color: '#f87171',
    desc: '最難関。強力な魔族と精霊が出現。15階まで。',
  },
  {
    id: 'boss_rush',
    name: 'ボスラッシュ',
    emoji: '💀',
    maxFloors: 10,
    theme: 'dungeon',
    enemyTypes: [],
    enemyCountBase: 0,
    diffMult: 1.0,
    bossRush: true,
    bossName: '試練の番人',
    color: '#f43f5e',
    desc: '連続ボス戦。10波クリアで真の覇者。',
  },
  {
    id: 'infinite_abyss',
    name: '奈落の底',
    emoji: '♾',
    maxFloors: 9999,
    infinite: true,       // 無限フロア
    theme: 'dungeon',
    enemyTypes: ['death_knight', 'void_crawler', 'fire_elemental', 'ice_elemental', 'thunder_elemental',
                 'vampire', 'lich', 'soul_eater', 'void_stalker', 'iron_golem', 'nightmare',
                 'chaos_mage', 'stone_golem', 'gargoyle', 'dark_slime', 'sniper', 'crossbowman',
                 'demon', 'goblin', 'archer', 'skeleton', 'skeleton_archer', 'zombie', 'wraith'],
    enemyCountBase: 12,
    diffMult: 1.0,        // フロアに応じて動的スケール
    bossName: '奈落の番人',
    color: '#a855f7',
    desc: '終わりなき深淵。フロアが深くなるほど敵が強くなる。レジェンダリ装備が出やすい。',
  },
];
